### ISSUE TITLE
Basic example doesn't work with v2.0.2

### ISSUE THREAD

**Issue by jamealg** [Irrelon/nextjs-morph-page#3]
It looks like individual element morphing was broken sometime after 1.0.2. The basic example uses 1.0.2 but the latest from NPM is 2.0.2. If you upgrade the package in that example it breaks morphing. There aren't any error messages so I'm not sure what's going on. Is there a new API for individual elements?

Thanks for making this by the way!

**Comment by Irrelon** [comment]
Thanks for the heads up! I've updated the package with a fixed example running on the new version and also updated the readme a bit as well.
